# Generated by Django 4.2 on 2024-07-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toDoList", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(default="Tasks", max_length=100),
            preserve_default=False,
        ),
    ]
